CONTRACT_MAP = {
    "AEX": {"code": "AE", "cycle": "FGHJKMNQUVXZ", "exchange": "EuronextInd"},
    "ASX": {"code": "AP", "cycle": "HMUZ", "exchange": "SFE"},
    "AUD": {"code": "A6", "cycle": "HMUZ", "exchange": "CME"},
    "BITCOIN": {"code": "BA", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "BOBL": {"code": "HR", "cycle": "HMUZ", "exchange": "EUREX"},
    "BRE": {"code": "L6", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "BRENT_W": {"code": "CB", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "BTP": {"code": "II", "cycle": "HMUZ", "exchange": "EUREX"},
    "BUND": {"code": "GG", "cycle": "HMUZ", "exchange": "EUREX"},
    "BUXL": {"code": "GX", "cycle": "HMUZ", "exchange": "EUREX"},
    "CAC": {"code": "MX", "cycle": "FGHJKMNQUVXZ", "exchange": "EuronextInd"},
    "CAD": {"code": "D6", "cycle": "HMUZ", "exchange": "CME"},
    "CANOLA": {"code": "RS", "cycle": "FHKNX", "exchange": "ICE/CA"},
    "CHF": {"code": "S6", "cycle": "HMUZ", "exchange": "CME"},
    "CHFJPY": {"code": "UP", "cycle": "HMUZ", "exchange": "CME"},
    "COCOA_LDN": {"code": "CA", "cycle": "HKNUZ", "exchange": "ICE/EU"},
    "COCOA_NY": {"code": "CC", "cycle": "HKNUZ", "exchange": "ICE/US"},
    "COFFEE": {"code": "KC", "cycle": "HKNUZ", "exchange": "ICE/US"},
    "COPPER": {"code": "HG", "cycle": "FHJMNUVZ", "exchange": "COMEX"},
    "CORN": {"code": "ZC", "cycle": "HKNUZ", "exchange": "CBOT"},
    "COTTON2": {"code": "CT", "cycle": "HKNVZ", "exchange": "ICE/US"},
    "CRUDE_W": {"code": "CL", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "DAX": {"code": "DY", "cycle": "HMUZ", "exchange": "EUREX"},
    "DOW": {"code": "YM", "cycle": "HMUZ", "exchange": "CBOT"},
    "DX": {"code": "DX", "cycle": "HMUZ", "exchange": "ICE/US"},
    "EUA": {"code": "CK", "cycle": "FGHJKMNQUVXZ", "days_count": 800, "exchange": "ENDEX"},
    "EUR": {"code": "E6", "cycle": "HMUZ", "exchange": "CME"},
    "EURCAD": {"code": "EP", "cycle": "HMUZ", "exchange": "ICE/US"},
    "EURCHF": {"code": "RF", "cycle": "HMUZ", "exchange": "CME"},
    "EURGBP": {"code": "RP", "cycle": "HMUZ", "exchange": "CME"},
    "EURIBOR": {"code": "IM", "cycle": "HMUZ", "exchange": "ICE"},
    "EUROSTX": {"code": "FX", "cycle": "HMUZ", "exchange": "EUREX"},
    "EURO600": {"code": "FY", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-BANKS": {"code": "FA", "cycle": "HMUZ", "exchange": "EUREX"},
    "EU-REALESTATE": {"code": "M4", "cycle": "HMUZ", "exchange": "EUREX"},
    "FED": {"code": "ZQ", "cycle": "FGHJKMNQUVXZ", "exchange": "CBOT"},
    "FEEDCOW": {"code": "GF", "cycle": "FHJKQUVX", "exchange": "CME"},
    "FTSE100": {"code": "X", "cycle": "HMUZ", "exchange": "ICE"},
    "FTSECHINAA": {"code": "HN", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "GAS_NL": {"code": "TG", "cycle": "FGHJKMNQUVXZ", "exchange": "ENDEX"},
    "GAS_UK": {"code": "NF", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "GAS_US": {"code": "NG", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GASOIL": {"code": "LF", "cycle": "FGHJKMNQUVXZ", "exchange": "ICE/EU/Com"},
    "GASOLINE": {"code": "RB", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "GBP": {"code": "B6", "cycle": "HMUZ", "exchange": "CME"},
    "GBPCHF": {"code": "SS", "cycle": "HMUZ", "exchange": "ICE/US"},
    "GBPJPY": {"code": "UR", "cycle": "HMUZ", "exchange": "CME"},
    "GILT": {"code": "G", "cycle": "HMUZ", "exchange": "ICE"},
    "GOLD": {"code": "GC", "cycle": "GJMQVZ", "exchange": "COMEX"},
    "HEATOIL": {"code": "HO", "cycle": "FGHJKMNQUVXZ", "exchange": "NYMEX"},
    "HANG": {"code": "HS", "cycle": "FGHJKMNQUVXZ", "exchange": "HKFE"},
    "IBEX": {"code": "EF", "cycle": "HMUZ", "exchange": "MEFF"},
    "IRON": {"code": "C0", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "JGB": {"code": "JX", "cycle": "HMUZ", "exchange": "SGX"},
    "JPY": {"code": "J6", "cycle": "HMUZ", "exchange": "CME"},
    "JSE40": {"code": "LX", "cycle": "HMUZ", "exchange": "SAFEX"},
    "KRWUSD_mini": {"code": "K9", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "LEANHOG": {"code": "HE", "cycle": "GJKMNQVZ", "exchange": "CME"},
    "LIVECOW": {"code": "LE", "cycle": "GJMQVZ", "exchange": "CME"},
    "LUMBER-new": {"code": "LB", "cycle": "FHKNUX", "exchange": "CME"},
    "MSCISING": {"code": "SV", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "MILK3": {"code": "DL", "cycle": "FGHJKMNQUVXZ", "exchange": "CME"},
    "MILLWHEAT": {"code": "ML", "cycle": "HKUZ", "exchange": "EuronextCom"},
    "MXP": {"code": "M6", "cycle": "HMUZ", "exchange": "CME"},
    "MUMMY": {"code": "S.", "cycle": "HMUZ", "exchange": "JPX"},
    "NASDAQ": {"code": "NQ", "cycle": "HMUZ", "exchange": "CME"},
    "NIFTY": {"code": "NH", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "NIKKEI": {"code": "NY", "cycle": "HMUZ", "exchange": "CME"},
    "NOK": {"code": "NR", "cycle": "HMUZ", "exchange": "CME"},
    "NZD": {"code": "N6", "cycle": "HMUZ", "exchange": "CME"},
    "OAT": {"code": "FN", "cycle": "HMUZ", "exchange": "EUREX"},
    "OATIES": {"code": "ZO", "cycle": "HKNUZ", "exchange": "CBOT"},
    "OJ": {"code": "OJ", "cycle": "FHKNUX", "exchange": "ICE/US"},
    "OMXS30": {"code": "OX", "cycle": "FGHJKMNQUVXZ", "exchange": "OMX"},
    "PALLAD": {"code": "PA", "cycle": "HMUZ", "exchange": "NYMEX"},
    "PLAT": {"code": "PL", "cycle": "FJNV", "exchange": "NYMEX"},
    "RICE": {"code": "ZR", "cycle": "FHKNUX", "exchange": "CBOT"},
    "ROBUSTA": {"code": "RM", "cycle": "FHKNUX", "exchange": "ICE/EU/Com"},
    "RUBBER": {"code": "W2", "cycle": "FGHJKMNQUVXZ", "exchange": "SGX"},
    "RUSSELL": {"code": "QR", "cycle": "HMUZ", "exchange": "CME"},
    "SEK": {"code": "SK", "cycle": "HMUZ", "exchange": "CME"},
    "SHATZ": {"code": "HF", "cycle": "HMUZ", "exchange": "EUREX"},
    "SILVER": {"code": "SI", "cycle": "HKNUZ", "exchange": "COMEX"},
    "SMI": {"code": "SZ", "cycle": "HMUZ", "exchange": "EUREX"},
    "SONIA3": {"code": "MZ", "cycle": "HMUZ", "exchange": "CME"},
    "SOYBEAN": {"code": "ZS", "cycle": "FHKNQUX", "exchange": "CBOT"},
    "SOYMEAL": {"code": "ZM", "cycle": "FHKNQUVZ", "exchange": "CBOT"},
    "SOYOIL": {"code": "ZL", "cycle": "FHKNQUVZ", "exchange": "CBOT"},
    "SP500": {"code": "ES", "cycle": "HMUZ", "exchange": "CME"},
    "SUGAR": {"code": "SW", "cycle": "HKQVZ", "days_count": 300, "exchange": "ICE/EU/Com"},
    "SUGAR11": {"code": "SB", "cycle": "HKNV", "days_count": 200, "exchange": "ICE/US"},
    "TOPIX": {"code": "TS", "cycle": "HMUZ", "exchange": "JPX"},
    "US10": {"code": "ZN", "cycle": "HMUZ", "exchange": "CBOT"},
    "US10U": {"code": "TN", "cycle": "HMUZ", "exchange": "CBOT"},
    "US2": {"code": "ZT", "cycle": "HMUZ", "exchange": "CBOT"},
    "US30": {"code": "UB", "cycle": "HMUZ", "exchange": "CME"},
    "US30Y": {"code": "ZB", "cycle": "HMUZ", "exchange": "CBOT"},
    "US5": {"code": "ZF", "cycle": "HMUZ", "exchange": "CBOT"},
    "V2X": {"code": "DV", "cycle": "FGHJKMNQUVXZ", "exchange": "EUREX"},
    "VIX": {"code": "VI", "cycle": "FGHJKMNQUVXZ", "exchange": "CFE"},
    "WHEAT": {"code": "ZW", "cycle": "HKNUZ", "exchange": "CBOT"},
    "WHEAT_ICE": {"code": "LW", "cycle": "FHKNUX", "days_count": 400, "exchange": "ICE/EU/Com"},
    "ZAR": {"code": "T6", "cycle": "HMUZ", "exchange": "CME"},
}

EXCHANGES = {
    "CBOT": {"tick_date": "2008-05-04", "eod_date": "1978-03-03"},
    "CFE": {"tick_date": "2009-11-24", "eod_date": "2004-04-02"},
    "CME": {"tick_date": "2008-05-05", "eod_date": "1978-03-23"},
    "COMEX": {"tick_date": "2008-05-04", "eod_date": "1978-02-27"},
    "ENDEX": {"tick_date": "2014-01-01", "eod_date": "2014-01-01"},
    "EUREX": {"tick_date": "1999-06-23", "eod_date": "1990-11-28"},
    "EuronextCom": {"tick_date": "2011-05-25", "eod_date": "2001-09-17"},
    "EuronextInd": {"tick_date": "2011-05-25", "eod_date": "2003-06-23"},
    "HKFE": {"tick_date": "2008-05-05", "eod_date": "1986-05-06"},
    "ICE": {"tick_date": "2008-05-04", "eod_date": "1978-08-07"},
    "ICE/CA": {"tick_date": "2008-05-04", "eod_date": "1979-01-23"},
    "ICE/EU/Com": {"tick_date": "2008-05-05", "eod_date": "1989-07-24"},
    "ICE/EU/Fin": {"tick_date": "1999-06-21", "eod_date": "1982-11-04"},
    "ICE/SG": {"tick_date": "2010-03-09", "eod_date": "2010-03-09"},
    "ICE/US": {"tick_date": "2008-05-04", "eod_date": "1978-08-07"},
    "JPX": {"tick_date": "1992-01-06", "eod_date": "1992-01-06"},
    "KCBT": {"tick_date": "2008-07-14", "eod_date": "1979-03-26"},
    "MEFF": {"tick_date": "1992-09-29", "eod_date": "1992-09-29"},
    "NYMEX": {"tick_date": "2008-05-05", "eod_date": "1978-05-15"},
    "OMX": {"tick_date": "2012-01-27", "eod_date": "2012-01-27"},
    "SAFEX": {"tick_date": "2004-01-02", "eod_date": "2004-01-02"},
    "SFE": {"tick_date": "2019-11-03", "eod_date": "1980-01-02"},
    "SGX": {"tick_date": "2008-05-05", "eod_date": "1986-09-03"},
    "TMX": {"tick_date": "2010-04-05", "eod_date": "1993-04-22"},
}
